### ISSUE TITLE
Could not find android-chat-ui.jar

### ISSUE THREAD

**Issue by alim096** [timigod/android-chat-ui#1]
I get this error after adding your dependency to the build.gradle file. It's looking for a .jar file but your repo has a .pom file. What am I doing wrong?

![selection_009](https://cloud.githubusercontent.com/assets/17227259/20860996/350b9b48-b985-11e6-9edc-024d2c389b31.png)

**Comment by timigod** [comment]
JCenter sent me a message saying my library has been added but apparently it was not. Do this instead (for now).

```
repositories {
    maven {
        url 'https://dl.bintray.com/timigod/maven/'
    }
}

...

dependencies {
    compile 'co.intentservice:android-chat-ui:0.1.1'
}

```

I'll update the readme to reflect this.

**Comment by timigod** [comment]
I made a mistake with module naming.

This will work.
```
compile 'co.intentservice.android-chat-ui:chat-ui:0.1.1'
```

**Comment by carloscrono** [comment]
Hi, I would like to use this ui but I got this error:

java.lang.NoSuchFieldError: chat_list
	at co.intentservice.chatui.ChatView.initializeViews(ChatView.java:101)
	at co.intentservice.chatui.ChatView.init(ChatView.java:91)
	at co.intentservice.chatui.ChatView.<init>(ChatView.java:84)
	at co.intentservice.chatui.ChatView.<init>(ChatView.java:79)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.jetbrains.android.uipreview.ViewLoader.createNewInstance(ViewLoader.java:465)
	at org.jetbrains.android.uipreview.ViewLoader.loadClass(ViewLoader.java:172)
	at org.jetbrains.android.uipreview.ViewLoader.loadView(ViewLoader.java:105)
	at com.android.tools.idea.rendering.LayoutlibCallbackImpl.loadView(LayoutlibCallbackImpl.java:186)
	at android.view.BridgeInflater.loadCustomView(BridgeInflater.java:334)
	at android.view.BridgeInflater.loadCustomView(BridgeInflater.java:345)
	at android.view.BridgeInflater.createViewFromTag(BridgeInflater.java:245)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
	at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:858)
	at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:70)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:834)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.inflate(RenderSessionImpl.java:324)
	at com.android.layoutlib.bridge.Bridge.createSession(Bridge.java:429)
	at com.android.ide.common.rendering.LayoutLibrary.createSession(LayoutLibrary.java:389)
	at com.android.tools.idea.rendering.RenderTask$2.compute(RenderTask.java:548)
	at com.android.tools.idea.rendering.RenderTask$2.compute(RenderTask.java:533)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:966)
	at com.android.tools.idea.rendering.RenderTask.createRenderSession(RenderTask.java:533)
	at com.android.tools.idea.rendering.RenderTask.lambda$inflate$70(RenderTask.java:659)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by oudavid** [comment]
I'm getting the following error:

Error:Could not find co.intentservice.android-chat-ui:chat-ui:0.1.1.
